MBTI/urls.py
from django.urls import path
from . import views

app_name = 'mbti'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('<int:question_pk>/', views.question_page, name='question_page'),
    path('<str:mbti>/', views.result_page, name='result_page'),
    path('<str:mbti>/share/', views.share_result_page, name='share_result_page'),
]

mbti_sideproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    path('admin/', admin.site.urls),

    path('mbti/', include('MBTI.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MBTI/models.py
from django.db import models

class Question(models.Model):
    title = models.TextField()
    choice_right = models.TextField()
    choice_left = models.TextField()
    question_category = models.TextField()

class Mbti(models.Model):
    mbti_name = models.TextField()
    title = models.TextField()
    mbti_type = models.TextField()
    best_mbti = models.IntegerField(default=0)
    worst_mbti = models.IntegerField(default=0)
    top_image = models.ImageField(null=True, blank=True)
    view_cnt = models.IntegerField(default=0)

class BaseInfo(models.Model):
    mbti = models.ForeignKey( 
        Mbti,
        on_delete=models.CASCADE,
        related_name= 'base_info'
    )
    content = models.TextField()

class Howto(models.Model):
    mbti = models.ForeignKey(
        Mbti,
        on_delete=models.CASCADE,
        related_name= 'how_to'
    )
    content = models.TextField()

MBTI/views.py
from django.shortcuts import (render, redirect, get_object_or_404)

from .models import Mbti, BaseInfo, Howto, Question

# Create your views here.


def main_page(request):
    # 비정상적인 접근 막기! (초기값 다르게,, 전체 문항 안고르면 메인으로 돌려버리기)
    mbties = Mbti.objects.all()
    viewers = 0
    max_viewers = 0
    min_viewers = 10e6

    for mbti in mbties:
        viewers += mbti.view_cnt

        if max_viewers < mbti.view_cnt:
            max_viewers = mbti.view_cnt
            max_mbti = mbti.mbti_name
            max_mbti_type = mbti.mbti_type
        
        if min_viewers > mbti.view_cnt:
            min_viewers = mbti.view_cnt
            min_mbti = mbti.mbti_name
            min_mbti_type = mbti.mbti_type
    
    context = {
        'mbties' : mbties,
        'viewers' : viewers,
        'max_viewers' : max_viewers,
        'min_viewers' : min_viewers,
        'max_mbti' : max_mbti,
        'min_mbti' : min_mbti,
        'max_mbti_type' : max_mbti_type,
        'min_mbti_type' : min_mbti_type,
    }

    return render(request, 'MBTI/main_page.html', context)


def question_page(request, question_pk):
    global flag
    if question_pk == 12:
        flag = 1

    questions = get_object_or_404(Question, pk = question_pk)

    context = {
        'questions' : questions,
        'progress': (question_pk/12)*100
    }

    return render(request, 'MBTI/question_page.html', context)


def result_page(request, mbti):
    global flag
    mbti_names = Mbti.objects.filter(mbti_name = mbti)[0]
    base_infos = BaseInfo.objects.filter(mbti_id = mbti_names.pk)
    how_tos = Howto.objects.filter(mbti_id = mbti_names.pk)

    best_mbti = Mbti.objects.filter(pk = mbti_names.best_mbti)[0]
    worst_mbti = Mbti.objects.filter(pk = mbti_names.worst_mbti)[0]

    if flag:
        mbti_names.view_cnt += 1
        mbti_names.save()
        flag = 0

    context = {
        'title' : mbti_names.title,
        'mbti_type': mbti_names.mbti_type,
        'mbti_name' : mbti_names.mbti_name,
        'top_image': mbti_names.top_image,
        'best_mbti' : best_mbti,
        'worst_mbti' : worst_mbti,
        'base_infos' : base_infos,
        'how_tos' : how_tos,
    }

    return render(request, 'MBTI/result_page.html', context)


def share_result_page(request, mbti):
    mbti_names = Mbti.objects.filter(mbti_name = mbti)[0]
    base_infos = BaseInfo.objects.filter(mbti_id = mbti_names.pk)
    how_tos = Howto.objects.filter(mbti_id = mbti_names.pk)

    best_mbti = Mbti.objects.filter(pk = mbti_names.best_mbti)[0]
    worst_mbti = Mbti.objects.filter(pk = mbti_names.worst_mbti)[0]
    
    context = {
        'title' : mbti_names.title,
        'mbti_type': mbti_names.mbti_type,
        'mbti_name' : mbti_names.mbti_name,
        'top_image': mbti_names.top_image,
        'best_mbti' : best_mbti,
        'worst_mbti' : worst_mbti,
        'base_infos' : base_infos,
        'how_tos' : how_tos,
    }

    return render(request, 'MBTI/result_share.html', context)

MBTI/templates/MBTI/main_page.html
{% extends 'base.html' %}
{% load static %}

<h1>총 참여 인원: {{ viewers }}</h1>
<h1>가장 많은 유형: {{ max_mbti }}</h1>
<h1>가장 적은 유형: {{ min_mbti }}</h1>

{% block content %}
  <div class="mb-3 d-flex flex-column align-items-center">
    <img src="{%static 'title.png'%}" alt="" class="title-img w-75 px-3 py-2">
    <span class="res-subtitle mb-3">
      나의 개발티콘을 찾아보자!
    </span>
  </div>
  <img src="{%static 'main.gif'%}" alt="" class="main-img">
  <a href="javascript:click()" class="mt-4 mb-5 d-flex justify-content-center align-items-center start-box">
    <span class="start-font">
      START
    </span>
  </a>

  <div class="my-2 d-flex flex-column justify-content-center align-items-center info-box">
    <p class="infofont-s mb-1">참여자 수</p>
    <p class="infofont-l">{{ viewers }}</p>
  </div>
  <div class="my-2 d-flex flex-column justify-content-center align-items-center info-box">
    <p class="infofont-s mb-1">가장 많은 유형</p>
    <p class="infofont-l">{{ max_mbti }} '{{ max_mbti_type }}'</p>
  </div>
  <div class="my-2 d-flex flex-column justify-content-center align-items-center info-box">
    <p class="infofont-s mb-1">가장 적은 유형</p>
    <p class="infofont-l">{{ min_mbti }} '{{ min_mbti_type }}'</p>
  </div>
{% endblock content %}

{% block script %}
<script>
  function click() {
    const mbtiDict = {'1':0, '2':0, '3':0, '4':0, '5':0, '6':0, '7':0, '8':0, '9':0, '10':0, '11':0, '12':0}
    const testList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    localStorage.setItem('mbtiDict', JSON.stringify(mbtiDict));
    localStorage.setItem('testList', JSON.stringify(testList));

    location.href = '1/'
  }
</script>
{% endblock script %}

MBTI/templates/MBTI/question_page.html
{% extends 'base.html' %}

{% block content %}
  <!-- 질문 번호 -->
  <p class="question-number mb-1">Q{{questions.pk}}</p>
  <!-- 프로그레스 바 -->
  <div class="progress" style="height: 8px; background: #C4C4C4;">
    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%; background: #9559C5;" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <!-- 질문 -->
  <div class="question-box d-flex justify-content-start align-items-center">
    <p class="question-font ms-1">{{ questions.title | linebreaksbr }}</p>
  </div>
  <!-- 대답 버튼 -->
  <form id="choiceLeft" method="POST" data-question-id="{{ questions.pk }}" data-question-category="{{ questions.question_category }}">
    {% csrf_token %}
    <button class="answer-box answer-font mt-3 mb-2 d-flex justify-content-center align-items-center border-0">
      <p class="m-0">
        {{ questions.choice_left | linebreaksbr }}
      </p>
    </button>
  </form>

  <form id="choiceRight" method="POST" data-question-id="{{ questions.pk }}" data-question-category="{{ questions.question_category }}">
    {% csrf_token %}
    <button class="answer-box answer-font mt-3 mb-2 d-flex justify-content-center align-items-center border-0">
      <p class="m-0">
        {{ questions.choice_right | linebreaksbr }}
      </p>
    </button>
  </form>
  
{% endblock content %}

{% block script %}
  <script>
    const loadMbti = JSON.parse(localStorage.getItem('mbtiDict'))
    const loadList = JSON.parse(localStorage.getItem('testList'))

    if (loadMbti === null) {
      location.href = `/mbti/`;
    }

    function onLeftSubmit(event) {
      event.preventDefault()
      const questionPk = event.target.dataset.questionId

      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
      const config = {
        headers: {'X-CSRFToken': csrftoken},
      }

      if (questionPk*1 === 12) {
        const questionType = event.target.dataset.questionCategory

        loadMbti[questionType] = 1
        
        const indexPk = questionPk - 1
        loadList[indexPk] = 1

        localStorage.setItem('mbtiDict', JSON.stringify(loadMbti));
        localStorage.setItem('testList', JSON.stringify(loadList));
        
        const newLoadMbti = JSON.parse(localStorage.getItem('mbtiDict'))
        const newLoadList = JSON.parse(localStorage.getItem('testList'))

        if (newLoadList.includes(0)) {
          swal({
            // swal html 태그 추가 후 클래스 입히기
            text: "응답하지 않은 문항이 있습니다.\n메인 페이지로 돌아갑니다.",
            button: true,
            className: "swal-custom"
          }).then(function(){location.href = `/mbti/`;})          
        } else {
          
          let mbtiString = ''
          const lastMbti = {'EI':0, 'NS':0, 'TF':0, 'PJ':0}
          //1,5,9-EI 2,4,7-TF 3,8,11-PJ 6,10,12-NS

          for (const [key, value] of Object.entries(newLoadMbti)) {
            if (value == 1) {
              if (['1','5','9'].includes(key)) {
                lastMbti.EI += 1
              } else if (['2','4','7'].includes(key)) {
                lastMbti.TF += 1
              } else if (['3','8','11'].includes(key)) {
                lastMbti.PJ += 1
              } else {
                lastMbti.NS += 1
              }
          }
        }

          for (const [key, value] of Object.entries(lastMbti)) {
            if (value >= 2) {
              mbtiString += key[0]
            } else {
              mbtiString += key[1]
            }
          }

          location.href = `/mbti/${mbtiString}/`
        }
      

      } else {
        const questionType = event.target.dataset.questionCategory

        loadMbti[questionPk] = 1
        
        const indexPk = questionPk - 1
        loadList[indexPk] = 1

        localStorage.setItem('mbtiDict', JSON.stringify(loadMbti));
        localStorage.setItem('testList', JSON.stringify(loadList));

        const newPk = questionPk*1 + 1
        
        location.href = `http://127.0.0.1:8000/mbti/${newPk}/`    
      }
    }

    const LeftSelect = document.querySelector(`#choiceLeft`)
    LeftSelect.addEventListener('submit', onLeftSubmit)

    function onRightSubmit(event) {
      event.preventDefault()

      const questionPk = event.target.dataset.questionId

      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
      const config = {
        headers: {'X-CSRFToken': csrftoken},
      }

      if (questionPk*1 === 12) {
        const questionType = event.target.dataset.questionCategory

        loadMbti[questionType] = 0
        
        const indexPk = questionPk - 1
        loadList[indexPk] = 1

        localStorage.setItem('mbtiDict', JSON.stringify(loadMbti));
        localStorage.setItem('testList', JSON.stringify(loadList));
        
        const newLoadMbti = JSON.parse(localStorage.getItem('mbtiDict'))
        const newLoadList = JSON.parse(localStorage.getItem('testList'))

        if (newLoadList.includes(0)) {
          swal({
            // swal html 태그 추가 후 클래스 입히기
            text: "응답하지 않은 문항이 있습니다.\n메인 페이지로 돌아갑니다.",
            button: true,
            className: "swal-custom"
          }).then(function(){location.href = `/mbti/`;})
        } else {
          
          let mbtiString = ''
          const lastMbti = {'EI':0, 'NS':0, 'TF':0, 'PJ':0}
          //1,5,9-EI 2,4,7-TF 3,8,11-PJ 6,10,12-NS

          for (const [key, value] of Object.entries(newLoadMbti)) {
            if (value == 1) {
              if (['1','5','9'].includes(key)) {
                lastMbti.EI += 1
              } else if (['2','4','7'].includes(key)) {
                lastMbti.TF += 1
              } else if (['3','8','11'].includes(key)) {
                lastMbti.PJ += 1
              } else {
                lastMbti.NS += 1
              }
            }
          }
          
          for (const [key, value] of Object.entries(lastMbti)) {
            if (value >= 2) {
              mbtiString += key[0]
            } else {
              mbtiString += key[1]
            }
          }
      
          location.href = `/mbti/${mbtiString}/`
        }

      } else {
        const questionType = event.target.dataset.questionCategory

        loadMbti[questionPk] = 0
        const indexPk = questionPk - 1
        loadList[indexPk] = 1

        localStorage.setItem('mbtiDict', JSON.stringify(loadMbti));
        localStorage.setItem('testList', JSON.stringify(loadList));

        const newPk = questionPk*1 + 1
        
        location.href = `/mbti/${newPk}/`    
      }
    }

    const RightSelect = document.querySelector(`#choiceRight`)
    RightSelect.addEventListener('submit', onRightSubmit)
  </script>
{% endblock script %}

MBTI/templates/MBTI/result_page.html
{% extends 'base.html' %}
{% load static %}

{% block copyJs %}
  <script src ="{% static 'result.js' %}"></script>
{% endblock copyJs %}

{% block content %}
  <!-- 로딩 이미지 -->
  <div id="loading" class="w-100 d-flex align-items-center h-90vh">
    <img src="{% static 'loading_img.gif' %}" alt="" class="w-100">
  </div>
  <div id="result" style="display: none;">
    <!-- 결과 타이틀 -->
    <div class="d-flex flex-column align-items-center">
      <div class="res-subtitle">{{ title | linebreaksbr }}</div>
      <div class="res-maintitle px-2 my-2">'{{ mbti_type }}'</div>
      <div class="res-mbti">아마도 당신은 {{ mbti_name }}...?</div>
    </div>
  
    <!-- 결과 이미지 -->
    
    <img src="{% get_static_prefix %}{{ top_image }}" alt="res-main-img" class="main-img mt-4 mb-3">
  
    <!-- 결과 설명 -->
    <ul class="content-font pt-2 pb-3 pe-3 mt-2 mb-3 border">
      {% for info in base_infos %}
        <li class="mt-2">{{ info.content }}</li>
      {% endfor %}
    </ul>
    
    <!-- 나는 어떤 개발자? -->
    <p class="develop-title">{{ mbti_type }}는?</p>
    <ul class="develop-font pt-2 pb-3 pe-3 mt-2 mb-5 border">
      {% for how_to in how_tos %}
        <li class="mt-2">{{ how_to.content }}</li>
      {% endfor %}
    </ul>
    
    <!-- 최고 최악 궁합 -->
    <div class="w-100 row m-0">
      <div class="w-50 d-flex col-6 flex-column align-items-center p-0">
        <p class="chemi-title mb-2">우린 제법 잘 어울려요</p>
        <p class="chemi-name">{{ best_mbti.mbti_type }} - {{ best_mbti.mbti_name }}</p>
        <img src="{% get_static_prefix %}{{ best_mbti.top_image }}" alt="best-chemi-img" class="chemi-img">
      </div>
      <div class="w-50 d-flex col-6 flex-column align-items-center p-0">
        <p class="chemi-title mb-2">당신과는 천천히</p>
        <p class="chemi-name">{{ worst_mbti.mbti_type }} - {{ worst_mbti.mbti_name }}</p>
        <img src="{% get_static_prefix %}{{ worst_mbti.top_image }}" alt="worst-chemi-img" class="chemi-img">
      </div>
    </div>
  
    <hr class="my-3">
  
    <a href="{% url 'mbti:main_page' %}" class="mt-2 mb-4 d-flex justify-content-center align-items-center start-box">
      <span class="start-font">
        다시하기
      </span>
    </a>
    <div class="d-flex justify-content-center my-2">
      <a id="btnTwitter" class="mx-2" href="javascript:shareTwitter()"><img class="sns-img" src="{%static 'images/icon-twitter.png'%}" alt=""></a>
      <a id="btnFacebook" class="mx-2" href="javascript:shareFacebook()"><img class="sns-img" src="{%static 'images/icon-facebook.png'%}" alt=""></a>    
      <a id="btnKakao" class="mx-2" href="javascript:shareKakao()"><img class="sns-img" src="{%static 'images/icon-kakao.png'%}" alt=""></a>  
      <a class="mx-2" href="javascript:clipURL()"><img class="sns-img" src="{%static 'images/url.png'%}" alt=""></a>  
    </div>
  </div>
{% endblock content %}

{% block script %}
<script>
  // 로딩할 때 필요한 함수
  
  document.addEventListener('DOMContentLoaded', (event) => {
    setTimeout(function() {
      const loading = document.querySelector('#loading')
      const result = document.querySelector('#result')
      loading.classList.remove('d-flex')
      loading.classList.remove('align-items-center')
      loading.style.display = 'none'
      result.style.display = 'block'
    }, 3000);
  })

  const testList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  localStorage.setItem('testList', JSON.stringify(testList));

</script>
{% endblock script %}

MBTI/templates/MBTI/result_share.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- 결과 타이틀 -->
  <div class="d-flex flex-column align-items-center">
    <div class="res-subtitle">내 친구에게 어울리는 개발자는?</div>
    <div class="res-maintitle px-2 my-2">'{{ mbti_type }}'</div>
    <div class="res-mbti">아마도 그 사람은 {{ mbti_name }}...?</div>
  </div>

  <!-- 결과 이미지 -->
  <img src="{% get_static_prefix %}{{ top_image }}" alt="res-main-img" class="main-img mt-4 mb-3">

  <!-- 결과 설명 -->
  <ul class="content-font pt-2 pb-3 pe-3 mt-2 mb-3 border">
    {% for info in base_infos %}
      <li class="mt-2">{{ info.content }}</li>
    {% endfor %}
  </ul>

  <!-- 나는 어떤 개발자? howto for문 수정 -->
  <p class="develop-title">{{mbti_type}}는?</p>
  <ul class="develop-font pt-2 pb-3 pe-3 mt-2 mb-5 border">
    <li class="mt-2">하고 싶은 일을 만나면 브레이크가 고장난 8톤 트럭이 되고, 하기 싫은 일을 만나면 브레이크가 과하게 잘 작동되다.</li>
    <li class="mt-2">(약속 Before) 귀찮아 귀찮아 귀찮아 나가기 싫어 나가기 싫어 => (약속 after) 오늘 너무 꿀잼이고 ~ 담에 또 봐야겠다 ~</li>
    <li class="mt-2">어떠한 상황에서도 페이커급의 반응속도로 대처한다.</li>
  </ul>
  
  <!-- 최고 최악 궁합 -->
  <div class="w-100 row m-0">
    <div class="w-50 d-flex col-6 flex-column align-items-center p-0">
      <p class="chemi-title mb-2">우린 제법 잘 어울려요</p>
      <p class="chemi-name">{{ best_mbti.mbti_type }}</p>
      <img src="{% get_static_prefix %}{{ best_mbti.top_image }}" alt="best-chemi-img" class="chemi-img">
    </div>
    <div class="w-50 d-flex col-6 flex-column align-items-center p-0">
      <p class="chemi-title mb-2">당신과는 천천히</p>
      <p class="chemi-name">{{ worst_mbti.mbti_type }}</p>
      <img src="{% get_static_prefix %}{{ worst_mbti.top_image }}" alt="worst-chemi-img" class="chemi-img">
    </div>
  </div>

  <hr class="my-3">

  <a href="{% url 'mbti:main_page' %}" class="mt-2 mb-4 d-flex justify-content-center align-items-center start-box">
    <span class="start-font">
      ♪ 나도 하기 ♪
    </span>
  </a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% load static %}
  <link href="{% static 'mbti.css' %}" rel="stylesheet">
  {% block copyJs %}
  {% endblock copyJs %}
</head>
<body>
  {% comment %} 상단 여백 {% endcomment %}
  <div style="height : 40px;"></div>
  
  {% comment %} 상속 {% endcomment %}
  <div class="my-container mx-auto">
    {% block content %}
    {% endblock content %}
  </div>
  
  {% comment %} footer {% endcomment %}
  <div style="height : 50px;"></div>
  <footer>
    <div class="fixed-bottom d-flex justify-content-center align-items-center footer-box">
      <span class="footer-font">
        Copyright 2022, 막내온탑 ALL RIGHTS RESEVED
      </span>
    </div>
  </footer>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  
  {% block script %}
  {% endblock script %}
  
</body>
</html>